import { Client, ClientStatus, Folder, FolderStatus, Document, DocumentProcessingStatus, PaymentStatus, User } from './types';

// Mock Users
export const MOCK_SUPER_ADMIN_USER: User = {
  id: 'SA001',
  name: 'Super Admin',
  email: 'superadmin@finaiq.com',
  role: 'SuperAdmin',
  avatarUrl: 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?q=80&w=200&auto=format&fit=crop',
  phone: '111-222-3333',
  team: 'Platform Administration',
  memberSince: '2022-01-01',
};

export const MOCK_ADMIN_USER: User = {
  id: 'A001',
  name: 'Sagar Agrobeet',
  email: 'admin@finaiq.com',
  role: 'Admin',
  avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&auto=format&fit=crop',
  phone: '123-456-7890',
  team: 'Platform Operations',
  memberSince: '2022-08-22',
};

export const MOCK_CLIENT_USER: User = {
  id: 'U001',
  name: 'John Doe',
  email: 'client@innovate.com',
  role: 'Client',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
  phone: '555-111-2222',
  team: 'Innovate Inc.',
  memberSince: '2023-01-15',
  clientId: 'C001',
  folderId: 'F001'
};


export const MOCK_ADMIN_USER_2: User = {
  id: 'A002',
  name: 'Jane Smith',
  email: 'admin2@finaiq.com',
  role: 'Admin',
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
  phone: '987-654-3210',
  team: 'Client Success',
  memberSince: '2023-01-10',
};

export const MOCK_ADMIN_USERS: User[] = [MOCK_ADMIN_USER, MOCK_ADMIN_USER_2];


export const MOCK_CLIENTS: Client[] = [
  { 
    id: 'C001', 
    companyName: 'Innovate Inc.', 
    contactName: 'John Doe', 
    email: 'john.doe@innovate.com', 
    phone: '123-456-7890', 
    status: ClientStatus.Active,
    address: '123 Innovation Drive, Tech City, 12345',
    notes: 'Long-term client, high volume.',
    accountCreated: '2022-08-22',
    lastActivity: '2025-08-21',
    monthlyGrowth: 2.2,
    folderId: 'F001',
    integration: 'No integration connected',
    approvedDocs: 118,
    pendingDocs: 11,
    rejectedDocs: 7,
    adminId: 'A001',
  },
  { 
    id: 'C002', 
    companyName: 'Synergy Solutions', 
    contactName: 'Jane Smith', 
    email: 'jane.smith@synergy.com', 
    phone: '234-567-8901', 
    status: ClientStatus.Active,
    address: '456 Synergy Ave, Business Park, 67890',
    notes: 'Migrating from competitor.',
    accountCreated: '2023-01-15',
    lastActivity: '2025-08-20',
    monthlyGrowth: 1.5,
    folderId: 'F002',
    integration: 'QuickBooks',
    approvedDocs: 250,
    pendingDocs: 5,
    rejectedDocs: 2,
    adminId: 'A001',
  },
  { 
    id: 'C003', 
    companyName: 'Apex Enterprises', 
    contactName: 'Sam Wilson', 
    email: 'sam.wilson@apex.com', 
    phone: '345-678-9012', 
    status: ClientStatus.Inactive,
    address: '789 Apex Lane, Suite 100, 11223',
    notes: 'Account on hold.',
    accountCreated: '2021-11-30',
    lastActivity: '2024-05-10',
    monthlyGrowth: 0,
    folderId: 'F003',
    integration: 'No integration connected',
    approvedDocs: 50,
    pendingDocs: 0,
    rejectedDocs: 1,
    adminId: 'A001',
  },
  { 
    id: 'C004', 
    companyName: 'Quantum Dynamics', 
    contactName: 'Emily Brown', 
    email: 'emily.b@quantum.com', 
    phone: '456-789-0123', 
    status: ClientStatus.Active,
    address: '101 Quantum Blvd, Science City, 44556',
    notes: '',
    accountCreated: '2023-03-10',
    lastActivity: '2025-08-19',
    monthlyGrowth: 3.1,
    folderId: 'F004',
    integration: 'API Connection',
    approvedDocs: 300,
    pendingDocs: 25,
    rejectedDocs: 12,
    adminId: 'A001',
  },
  { 
    id: 'C005', 
    companyName: 'Stellar Corp', 
    contactName: 'Michael Clark', 
    email: 'm.clark@stellar.com', 
    phone: '567-890-1234', 
    status: ClientStatus.Active,
    address: '210 Galaxy Way, Starport, 77889',
    notes: 'Needs custom workflow.',
    accountCreated: '2022-05-20',
    lastActivity: '2025-08-22',
    monthlyGrowth: 1.8,
    folderId: 'F005',
    integration: 'No integration connected',
    approvedDocs: 180,
    pendingDocs: 0,
    rejectedDocs: 4,
    adminId: 'A001',
  },
  {
    id: 'C006',
    companyName: 'NextGen Innovations',
    contactName: 'Chris Lee',
    email: 'chris.lee@nextgen.com',
    phone: '678-901-2345',
    status: ClientStatus.Active,
    address: '321 Future St, Metropolis, 98765',
    notes: 'Early adopter of new features.',
    accountCreated: '2023-08-01',
    lastActivity: '2025-08-22',
    monthlyGrowth: 4.5,
    folderId: 'F006',
    integration: 'Salesforce',
    approvedDocs: 450,
    pendingDocs: 15,
    rejectedDocs: 8,
    adminId: 'A001',
  },
  {
    id: 'C007',
    companyName: 'Oceanic Goods',
    contactName: 'Patricia Green',
    email: 'pat.g@oceanic.com',
    phone: '789-012-3456',
    status: ClientStatus.Inactive,
    address: '555 Maritime Way, Port City, 54321',
    notes: 'Seasonal business, currently off-season.',
    accountCreated: '2022-02-10',
    lastActivity: '2025-03-15',
    monthlyGrowth: 0.2,
    folderId: 'F007',
    integration: 'No integration connected',
    approvedDocs: 95,
    pendingDocs: 0,
    rejectedDocs: 3,
    adminId: 'A001',
  },
  {
    id: 'C008',
    companyName: 'Global Logistics',
    contactName: 'Robert Hill',
    email: 'rob.hill@globallog.com',
    phone: '890-123-4567',
    status: ClientStatus.Active,
    address: '123 Supply Chain Rd, Distribution Hub, 13579',
    notes: '',
    accountCreated: '2023-10-05',
    lastActivity: '2025-08-20',
    monthlyGrowth: 2.8,
    folderId: 'F008',
    integration: 'API Connection',
    approvedDocs: 620,
    pendingDocs: 30,
    rejectedDocs: 10,
    adminId: 'A002',
  },
  {
    id: 'C009',
    companyName: 'HealthCo.',
    contactName: 'Linda Carter',
    email: 'l.carter@healthco.com',
    phone: '901-234-5678',
    status: ClientStatus.Active,
    address: '789 Wellness Ave, Clinic Town, 24680',
    notes: 'HIPAA compliance required.',
    accountCreated: '2021-06-20',
    lastActivity: '2025-08-18',
    monthlyGrowth: 1.9,
    folderId: 'F009',
    integration: 'No integration connected',
    approvedDocs: 320,
    pendingDocs: 4,
    rejectedDocs: 6,
    adminId: 'A002',
  },
  {
    id: 'C010',
    companyName: 'Creative Minds',
    contactName: 'Tom White',
    email: 'tom.w@creative.com',
    phone: '012-345-6789',
    status: ClientStatus.Active,
    address: '456 Design St, Arts District, 97531',
    notes: 'Requires high-res image processing.',
    accountCreated: '2023-05-12',
    lastActivity: '2025-08-21',
    monthlyGrowth: 3.5,
    folderId: 'F010',
    integration: 'Dropbox',
    approvedDocs: 150,
    pendingDocs: 12,
    rejectedDocs: 5,
    adminId: 'A002',
  },
  {
    id: 'C011',
    companyName: 'SilverLine LLC',
    contactName: 'Jessica Blue',
    email: 'j.blue@silverline.com',
    phone: '111-222-3333',
    status: ClientStatus.Inactive,
    address: '1 Silver Rd, Old Town, 11111',
    notes: 'Paused subscription.',
    accountCreated: '2020-01-01',
    lastActivity: '2023-12-01',
    monthlyGrowth: -0.5,
    folderId: 'F011',
    integration: 'No integration connected',
    approvedDocs: 500,
    pendingDocs: 0,
    rejectedDocs: 20,
    adminId: 'A002',
  },
  {
    id: 'C012',
    companyName: 'Peak Performance',
    contactName: 'Mark Black',
    email: 'mark@peak.com',
    phone: '222-333-4444',
    status: ClientStatus.Active,
    address: '2 Peak Ave, Summit City, 22222',
    notes: 'High volume user.',
    accountCreated: '2022-09-15',
    lastActivity: '2025-08-22',
    monthlyGrowth: 5.1,
    folderId: 'F012',
    integration: 'API Connection',
    approvedDocs: 1200,
    pendingDocs: 50,
    rejectedDocs: 30,
    adminId: 'A002',
  },
  {
    id: 'C013',
    companyName: 'GreenLeaf Organics',
    contactName: 'Susan Green',
    email: 'susan.g@greenleaf.com',
    phone: '333-444-5555',
    status: ClientStatus.Active,
    address: '3 Farm Ln, Green Valley, 33333',
    notes: '',
    accountCreated: '2023-02-28',
    lastActivity: '2025-08-15',
    monthlyGrowth: 2.0,
    folderId: 'F013',
    integration: 'QuickBooks',
    approvedDocs: 80,
    pendingDocs: 8,
    rejectedDocs: 1,
    adminId: 'A002',
  },
  {
    id: 'C014',
    companyName: 'TechPioneers',
    contactName: 'Brian Gray',
    email: 'b.gray@techpioneers.com',
    phone: '444-555-6666',
    status: ClientStatus.Active,
    address: '4 Pioneer Pl, Innovation Hub, 44444',
    notes: 'Beta tester for new workflows.',
    accountCreated: '2022-11-11',
    lastActivity: '2025-08-20',
    monthlyGrowth: 3.9,
    folderId: 'F014',
    integration: 'No integration connected',
    approvedDocs: 750,
    pendingDocs: 22,
    rejectedDocs: 14,
    adminId: 'A002',
  },
  {
    id: 'C015',
    companyName: 'Digital Dreams',
    contactName: 'Laura Purple',
    email: 'laura.p@digitaldreams.com',
    phone: '555-666-7777',
    status: ClientStatus.Inactive,
    address: '5 Dream Dr, Virtual City, 55555',
    notes: 'Project completed.',
    accountCreated: '2023-07-07',
    lastActivity: '2024-07-07',
    monthlyGrowth: 0,
    folderId: 'F015',
    integration: 'No integration connected',
    approvedDocs: 120,
    pendingDocs: 0,
    rejectedDocs: 0,
    adminId: 'A002',
  },
];

export const MOCK_FOLDERS: Folder[] = [
  { id: 'F001', folderName: 'Innovate Inc.', documentCount: 8, status: FolderStatus.Active, clientId: 'C001' },
  { id: 'F002', folderName: 'Synergy Solutions', documentCount: 5, status: FolderStatus.Active, clientId: 'C002' },
  { id: 'F003', folderName: 'Apex Enterprises', documentCount: 0, status: FolderStatus.Archived, clientId: 'C003' },
  { id: 'F004', folderName: 'Quantum Dynamics', documentCount: 3, status: FolderStatus.PendingImport, clientId: 'C004' },
  { id: 'F005', folderName: 'Stellar Corp', documentCount: 0, status: FolderStatus.Active, clientId: 'C005' },
  { id: 'F006', folderName: 'NextGen Innovations', documentCount: 4, status: FolderStatus.Active, clientId: 'C006' },
  { id: 'F007', folderName: 'Oceanic Goods', documentCount: 0, status: FolderStatus.Archived, clientId: 'C007' },
  { id: 'F008', folderName: 'Global Logistics', documentCount: 0, status: FolderStatus.Active, clientId: 'C008' },
  { id: 'F009', folderName: 'HealthCo.', documentCount: 0, status: FolderStatus.Active, clientId: 'C009' },
  { id: 'F010', folderName: 'Creative Minds', documentCount: 0, status: FolderStatus.Active, clientId: 'C010' },
  { id: 'F011', folderName: 'SilverLine LLC', documentCount: 0, status: FolderStatus.Archived, clientId: 'C011' },
  { id: 'F012', folderName: 'Peak Performance', documentCount: 0, status: FolderStatus.Active, clientId: 'C012' },
  { id: 'F013', folderName: 'GreenLeaf Organics', documentCount: 0, status: FolderStatus.Active, clientId: 'C013' },
  { id: 'F014', folderName: 'TechPioneers', documentCount: 0, status: FolderStatus.Active, clientId: 'C014' },
  { id: 'F015', folderName: 'Digital Dreams', documentCount: 0, status: FolderStatus.Archived, clientId: 'C015' },
];

export const MOCK_DOCUMENTS: Document[] = [
    { 
      id: 'D001', 
      folderId: 'F001',
      supplier: 'Tech Solutions Ltd',
      invoiceNumber: 'INV-2024-001',
      date: '2025-01-15',
      amount: 2500,
      currency: 'USD',
      status: DocumentProcessingStatus.Ready,
      payment: PaymentStatus.Paid,
      dueDate: '2025-02-15'
    },
    { 
      id: 'D002', 
      folderId: 'F001',
      supplier: 'Office Supplies Co',
      invoiceNumber: 'INV-2024-002',
      date: '2025-01-18',
      amount: 750.5,
      currency: 'USD',
      status: DocumentProcessingStatus.ExportError,
      payment: PaymentStatus.Pending,
      dueDate: '2025-02-18'
    },
    { 
      id: 'D003', 
      folderId: 'F001',
      supplier: 'Marketing Agency',
      invoiceNumber: 'INV-2024-003',
      date: '2025-01-20',
      amount: 5000,
      currency: 'USD',
      status: DocumentProcessingStatus.ReviewRequired,
      payment: PaymentStatus.Overdue,
      dueDate: '2025-02-01'
    },
    { 
      id: 'D004', 
      folderId: 'F002',
      supplier: 'Synergy Parts',
      invoiceNumber: 'SYN-2024-119',
      date: '2025-02-05',
      amount: 1230.00,
      currency: 'USD',
      status: DocumentProcessingStatus.Ready,
      payment: PaymentStatus.Paid,
      dueDate: '2025-03-05'
    },
    // --- ADDED DOCUMENTS ---
    { 
      id: 'D005', 
      folderId: 'F001',
      supplier: 'Cloud Services',
      invoiceNumber: 'INV-2024-004',
      date: '2025-02-25',
      amount: 1200,
      currency: 'USD',
      status: DocumentProcessingStatus.Ready,
      payment: PaymentStatus.Paid,
      dueDate: '2025-03-25'
    },
    { 
      id: 'D006', 
      folderId: 'F001',
      supplier: 'Hardware Supplies',
      invoiceNumber: 'INV-2024-005',
      date: '2025-03-01',
      amount: 3500,
      currency: 'USD',
      status: DocumentProcessingStatus.Ready,
      payment: PaymentStatus.Pending,
      dueDate: '2025-04-01'
    },
    { 
      id: 'D007', 
      folderId: 'F001',
      supplier: 'Legal Consulting',
      invoiceNumber: 'INV-2024-006',
      date: '2025-03-05',
      amount: 7500,
      currency: 'USD',
      status: DocumentProcessingStatus.ReviewRequired,
      payment: PaymentStatus.Pending,
      dueDate: '2025-04-05'
    },
    { 
      id: 'D008', 
      folderId: 'F001',
      supplier: 'Software License',
      invoiceNumber: 'INV-2024-007',
      date: '2025-03-10',
      amount: 950,
      currency: 'USD',
      status: DocumentProcessingStatus.Ready,
      payment: PaymentStatus.Paid,
      dueDate: '2025-04-10'
    },
    { 
      id: 'D009', 
      folderId: 'F001',
      supplier: 'Office Supplies Co',
      invoiceNumber: 'INV-2024-008',
      date: '2025-03-12',
      amount: 450.75,
      currency: 'USD',
      status: DocumentProcessingStatus.ExportError,
      payment: PaymentStatus.Overdue,
      dueDate: '2025-03-20'
    },
    { 
      id: 'D010', 
      folderId: 'F002',
      supplier: 'Logistics Partner',
      invoiceNumber: 'SYN-2024-120',
      date: '2025-03-15',
      amount: 2200,
      currency: 'USD',
      status: DocumentProcessingStatus.Ready,
      payment: PaymentStatus.Paid,
      dueDate: '2025-04-15'
    },
    { 
      id: 'D011', 
      folderId: 'F002',
      supplier: 'Component Supplier',
      invoiceNumber: 'SYN-2024-121',
      date: '2025-03-18',
      amount: 1800.50,
      currency: 'USD',
      status: DocumentProcessingStatus.ReviewRequired,
      payment: PaymentStatus.Pending,
      dueDate: '2025-04-18'
    },
    { 
      id: 'D012', 
      folderId: 'F002',
      supplier: 'Synergy Parts',
      invoiceNumber: 'SYN-2024-122',
      date: '2025-03-20',
      amount: 850,
      currency: 'USD',
      status: DocumentProcessingStatus.Ready,
      payment: PaymentStatus.Paid,
      dueDate: '2025-04-20'
    },
     { 
      id: 'D013', 
      folderId: 'F002',
      supplier: 'Maintenance Corp',
      invoiceNumber: 'SYN-2024-123',
      date: '2025-03-22',
      amount: 550,
      currency: 'USD',
      status: DocumentProcessingStatus.Ready,
      payment: PaymentStatus.Pending,
      dueDate: '2025-04-22'
    },
    { 
      id: 'D014', 
      folderId: 'F004',
      supplier: 'Research Lab',
      invoiceNumber: 'QDI-2025-001',
      date: '2025-04-01',
      amount: 15000,
      currency: 'USD',
      status: DocumentProcessingStatus.ReviewRequired,
      payment: PaymentStatus.Pending,
      dueDate: '2025-05-01'
    },
    { 
      id: 'D015', 
      folderId: 'F004',
      supplier: 'Precision Instruments',
      invoiceNumber: 'QDI-2025-002',
      date: '2025-04-05',
      amount: 8750,
      currency: 'USD',
      status: DocumentProcessingStatus.Ready,
      payment: PaymentStatus.Paid,
      dueDate: '2025-05-05'
    },
     { 
      id: 'D016', 
      folderId: 'F004',
      supplier: 'Data Analytics Inc',
      invoiceNumber: 'QDI-2025-003',
      date: '2025-04-10',
      amount: 4500,
      currency: 'USD',
      status: DocumentProcessingStatus.Ready,
      payment: PaymentStatus.Pending,
      dueDate: '2025-05-10'
    },
    { 
      id: 'D017', 
      folderId: 'F006',
      supplier: 'Prototyping Co',
      invoiceNumber: 'NGI-001',
      date: '2025-05-01',
      amount: 6800,
      currency: 'USD',
      status: DocumentProcessingStatus.Ready,
      payment: PaymentStatus.Paid,
      dueDate: '2025-06-01'
    },
    { 
      id: 'D018', 
      folderId: 'F006',
      supplier: 'AI Services',
      invoiceNumber: 'NGI-002',
      date: '2025-05-05',
      amount: 12500,
      currency: 'USD',
      status: DocumentProcessingStatus.ReviewRequired,
      payment: PaymentStatus.Pending,
      dueDate: '2025-06-05'
    },
    { 
      id: 'D019', 
      folderId: 'F006',
      supplier: 'Cloud Services',
      invoiceNumber: 'NGI-003',
      date: '2025-05-10',
      amount: 3200,
      currency: 'USD',
      status: DocumentProcessingStatus.Ready,
      payment: PaymentStatus.Paid,
      dueDate: '2025-06-10'
    },
    { 
      id: 'D020', 
      folderId: 'F006',
      supplier: 'Marketing Agency',
      invoiceNumber: 'NGI-004',
      date: '2025-05-15',
      amount: 4800,
      currency: 'USD',
      status: DocumentProcessingStatus.ExportError,
      payment: PaymentStatus.Overdue,
      dueDate: '2025-05-25'
    },
];
